CREATE TABLE student
(
    ID VARCHAR2(6) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	DEPT_NAME VARCHAR2(3) NOT NULL,
	TOT_CREDIT INT,
  	CONSTRAINT PK_STUDENT PRIMARY KEY(ID),
  	CONSTRAINT TOT_CREDIT_CHECK CHECK (TOT_CREDIT < 180)
);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('00128', 'Zhang', 'CSE', 102);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('12345', 'Shankar', 'CSE', 32);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('19991', 'Brandt', 'HIS', 80);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('23121', 'Chavez', 'FIN', 110);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('44553', 'Peltier', 'PHY', 56);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('45678', 'Levy', 'PHY', 46);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('54321', 'Williams', 'CSE', 5);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('55739', 'Sanchez', 'MUS', 38);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('70557', 'Snow', 'PHY', 0);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('76543', 'Brown', 'CSE', 58);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('76653', 'Aoi', 'EEE', 60);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('98765', 'Bourikas', 'EEE', 9);
INSERT INTO student(ID, NAME, DEPT_NAME, TOT_CREDIT) VALUES
('98988', 'Tanaka', 'BIO', 120);
SELECT * FROM student;
SELECT NAME, DEPT_NAME FROM student WHERE TOT_CREDIT>=80 OR TOT_CREDIT<=120;
SELECT ID, NAME FROM student WHERE DEPT_NAME = 'CSE';
SELECT NAME, TOT_CREDIT FROM student WHERE DEPT_NAME = 'PHY'AND TOT_CREDIT<50;
SELECT DEPT_NAME FROM student WHERE NAME = 'Shankar'AND NAME = 'Sanchez';
SELECT NAME, MAX(TOT_CREDIT) FROM student;
SELECT DEPT_NAME, SUM(TOT_CREDIT) FROM student WHERE DEPT_NAME = 'PHY';
DELETE FROM student WHERE TOT_CREDIT<10;
DROP TABLE student;
